
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest mock
  - pip install .
before_script:
  - sleep 1
script:
  - pytest tests
after_success:
  - sleep 1